### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by Dedrus** [microsoft/wopi-validator-core#107]
When I'm trying to run tests, I receive the next error:
Used command from readme:
`dotnet run --project ./src/WopiValidator/WopiValidator.csproj --framework net6.0 -- -t MyAccessToken -l 0 -w http://localhost:8402/wopi/files/<id> -e OfficeOnline -s`

> System.ArgumentException: Could not find a prereq test case named {0} (Parameter 'SupportsCoauthPrereq')
   at Microsoft.Office.WopiValidator.Core.Factories.TestCaseFactory.GetPrereqTests(XElement definition, Dictionary`2 prereqsDictionary)+MoveNext() in C:\Users\anikolaev\dev\wopi-validator-core\src\WopiValidator.Core\Factories\TestCaseFactory.cs:line 43
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Office.WopiValidator.Core.ConfigParser.GetTestExecutionDataForGroup(XElement definition, Dictionary`2 prereqCasesDictionary, ITestCaseFactory testCaseFactory, IResourceManager resourceManager, TestCategory targetTestCategory) in C:\Users\anikolaev\dev\wopi-validator-core\src\WopiValidator.Core\ConfigParser.cs:line 52
   at Microsoft.Office.WopiValidator.Core.ConfigParser.<>c__DisplayClass1_0.<ParseExecutionData>b__1(XElement x) in C:\Users\anikolaev\dev\wopi-validator-core\src\WopiValidator.Core\ConfigParser.cs:line 38
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.Office.WopiValidator.Program.Execute(Options options) in C:\Users\anikolaev\dev\wopi-validator-core\src\WopiValidator\Program.cs:line 98
   at Microsoft.Office.WopiValidator.Program.<>c.<Main>b__1_0(Options options) in C:\Users\anikolaev\dev\wopi-validator-core\src\WopiValidator\Program.cs:line 46
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Microsoft.Office.WopiValidator.Program.Main(String[] args) in C:\Users\anikolaev\dev\wopi-validator-core\src\WopiValidator\Program.cs:line 44

**Comment by mikeebowen** [comment]
Hi @Dedrus , You need to change `<id>` to the id of your .wopitest file for your WOPI server

**Comment by Dedrus** [comment]
@mikeebowen thanks for help!
