### ISSUE TITLE
Test category option is not working

### ISSUE THREAD

**Issue by hagasper** [microsoft/wopi-validator-core#117]
Hello.

There seems to be a problem with providing test category option (-e) as an argument when running the WOPI Validator. It returns bellow error, when trying to specify category other than "All" (that is: "WopiCore" or "OfficeOnline"). So, if I don't provide test category or if I provide test category "All", the WOPI Validator runs normally, otherwise it fails. Seems like an issue in your source code.

`System.ArgumentException: Could not find a prereq test case named {0} (Parameter 'SupportsCoauthPrereq')
   at Microsoft.Office.WopiValidator.Core.Factories.TestCaseFactory.GetPrereqTests(XElement definition, Dictionary`2 prereqsDictionary)+MoveNext() in C:\Dev\wopi-validator-core\src\WopiValidator.Core\Factories\TestCaseFactory.cs:line 43
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Office.WopiValidator.Core.ConfigParser.GetTestExecutionDataForGroup(XElement definition, Dictionary`2 prereqCasesDictionary, ITestCaseFactory testCaseFactory, IResourceManager resourceManager, TestCategory targetTestCategory) in C:\Dev\wopi-validator-core\src\WopiValidator.Core\ConfigParser.cs:line 52
   at Microsoft.Office.WopiValidator.Core.ConfigParser.<>c__DisplayClass1_0.<ParseExecutionData>b__1(XElement x) in C:\Dev\wopi-validator-core\src\WopiValidator.Core\ConfigParser.cs:line 38
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.Office.WopiValidator.Program.Execute(Options options) in C:\Dev\wopi-validator-core\src\WopiValidator\Program.cs:line 98
   at Microsoft.Office.WopiValidator.Program.<>c.<Main>b__1_0(Options options) in C:\Dev\wopi-validator-core\src\WopiValidator\Program.cs:line 46
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Microsoft.Office.WopiValidator.Program.Main(String[] args) in C:\Dev\wopi-validator-core\src\WopiValidator\Program.cs:line 44`

I have the latest version of WOPI Validator available on Git.

Thanks.

**Comment by mvksaran** [comment]
I'm running into the same issue and when run with All, I see all the test cases skipped

**Comment by theilgaz** [comment]
Same issue. Any fix?
