### ISSUE TITLE
GetProofData throws ArgumentNullException if accesstoken is missing on the WopiRequest

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/wopi-validator-core#12]
```
System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at WopiValidator.Core.ProofKeysHelper.GetProofData(ProofKeyInput proofData)
   at WopiValidator.Core.ProofKeysHelper.GetSignedProofData(ProofKeyInput proofData, RSACryptoServiceProvider rsaAlg)
   at WopiValidator.Core.Requests.WopiRequest.GetProofKeyHeaders(String accessToken, Uri endpointUri, RSACryptoServiceProvider proofKeyProviderNew, RSACryptoServiceProvider proofKeyProviderOld)
   at WopiValidator.Core.Requests.WopiRequest.Execute(String endpointAddress, String accessToken, Int64 accessTokenTtl, ITestCase testCase, Dictionary`2 savedState, IResourceManager resourceManager, String userAgent, RSACryptoServiceProvider proofKeyProviderNew, RSACryptoServiceProvider proofKeyProviderOld)
   at WopiValidator.Core.TestCaseExecutor.ExecuteTestCase(ITestCase testCase)
   at Microsoft.Office.Web.WopiTestService.ExecuteTestMethod.ProcessRequest(HttpContext context)
```
Notes from chrisbro-MSFT:

I bet the Url property of the ContainerInfo objects returned by /files/EnumerateAncestors does not include an AccessToken.  There are only two calls to GetBytes in ProofKeyHelper.GetProofData() and one of them is on a field that couldn’t be null or we would have crashed already.  So it has to be access token.  And that test is defined like so:

```xml
<Requests>
       <EnumerateAncestors>
              <SaveState>
                     <State Name="ParentContainerUrl" Source="AncestorsWithRootFirst[-1:].Url" />
              </SaveState>
       </EnumerateAncestors>
       <CheckContainer OverrideUrl="$State:ParentContainerUrl">
 ```
 
Have seen this a couple of times.  Perhaps we should add a try..catch around WopiRequest.Execute() and have it return an IResponseData object that indicates the error.  Test would still fail but it will fail properly and the request info can be seen in the inspector tabs.

**Comment by petmat** [comment]
I'll give this a try!
