### ISSUE TITLE
System.ArgumentException: Could not find a prereq test case named {0} (Parameter 'SupportsCoauthPrereq')

### ISSUE THREAD

**Issue by tbswork1** [microsoft/wopi-validator-core#122]
Getting the above error running the following command:

` dotnet src\WopiValidator\bin\Release\net6.0\win-x64\Microsoft.Office.WopiValidator.dll --token "xxxxxxxxxxxxxxxxxxxxx" --token_ttl 0 --wopisrc http://localhost:2080/wopi/files/xxxxxxxxxxxxxxxx --testcategory OfficeOnline --ignore-skipped`

**Comment by cyndilopez** [comment]
+1 Seeing this as well

**Comment by EislerDavid** [comment]
Same issue here.

Command:
`dotnet Microsoft.Office.WopiValidator.dll --token XXXX --token_ttl 1724418272 --wopisrc https://XXXX/api/wopi/files/XXXX--testcategory OfficeOnline --ignore-skipped`

StackTrace:
```
System.ArgumentException: Could not find a prereq test case named {0} (Parameter 'SupportsCoauthPrereq')
   at Microsoft.Office.WopiValidator.Core.Factories.TestCaseFactory.GetPrereqTests(XElement definition, Dictionary`2 prereqsDictionary)+MoveNext() in C:\Users\XXXX\Source\Repos\wopi-validator-core\src\WopiValidator.Core\Factories\TestCaseFactory.cs:line 43
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Office.WopiValidator.Core.ConfigParser.GetTestExecutionDataForGroup(XElement definition, Dictionary`2 prereqCasesDictionary, ITestCaseFactory testCaseFactory, IResourceManager resourceManager, TestCategory targetTestCategory) in C:\Users\XXXX\Source\Repos\wopi-validator-core\src\WopiValidator.Core\ConfigParser.cs:line 52
   at Microsoft.Office.WopiValidator.Core.ConfigParser.<>c__DisplayClass1_0.<ParseExecutionData>b__1(XElement x) in C:\Users\XXXX\Source\Repos\wopi-validator-core\src\WopiValidator.Core\ConfigParser.cs:line 38
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.Office.WopiValidator.Program.Execute(Options options) in C:\Users\XXX\Source\Repos\wopi-validator-core\src\WopiValidator\Program.cs:line 98
   at Microsoft.Office.WopiValidator.Program.<>c.<Main>b__1_0(Options options) in C:\Users\XXXX\Source\Repos\wopi-validator-core\src\WopiValidator\Program.cs:line 46
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Microsoft.Office.WopiValidator.Program.Main(String[] args) in C:\Users\XXXX\Source\Repos\wopi-validator-core\src\WopiValidator\Program.cs:line 44
```

**Comment by qq312888991** [comment]
+1 Seeing this as well

**Comment by mvksaran** [comment]
+1 same issue

**Comment by naima-hossain** [comment]
Seeing the same issue here. Anyone able to by pass this? Or used a different wopi validator?
I am using the following command:
`dotnet src/WopiValidator/bin/Release/net6.0/osx-x64/publish/Microsoft.Office.WopiValidator.dll --token xxxxxxxxxxxx-xxxxxxx-x --token_ttl 0 --wopisrc https://wopi.cengage.com/services/v1/spreadsheet/wopi/files/<file-id> --testcategory OfficeOnline --ignore-skipped --config TestCases.xml`

Stacktrace:

``` System.ArgumentException: Could not find a prereq test case named {0} (Parameter 'SupportsCoauthPrereq')
   at Microsoft.Office.WopiValidator.Core.Factories.TestCaseFactory.GetPrereqTests(XElement definition, Dictionary`2 prereqsDictionary)+MoveNext() in /Users/****/Projects/wopi-validator-core/src/WopiValidator.Core/Factories/TestCaseFactory.cs:line 43
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Office.WopiValidator.Core.ConfigParser.GetTestExecutionDataForGroup(XElement definition, Dictionary`2 prereqCasesDictionary, ITestCaseFactory testCaseFactory, IResourceManager resourceManager, TestCategory targetTestCategory) in /Users/****/Projects/wopi-validator-core/src/WopiValidator.Core/ConfigParser.cs:line 52
   at Microsoft.Office.WopiValidator.Core.ConfigParser.<>c__DisplayClass1_0.<ParseExecutionData>b__1(XElement x) in /Users/****/Projects/wopi-validator-core/src/WopiValidator.Core/ConfigParser.cs:line 38
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.Office.WopiValidator.Program.Execute(Options options) in /Users/*****/Projects/wopi-validator-core/src/WopiValidator/Program.cs:line 98
   at Microsoft.Office.WopiValidator.Program.<>c.<Main>b__1_0(Options options) in /Users/*****/Projects/wopi-validator-core/src/WopiValidator/Program.cs:line 46
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Microsoft.Office.WopiValidator.Program.Main(String[] args) in /Users/*****/Projects/wopi-validator-core/src/WopiValidator/Program.cs:line 44```

**Comment by EislerDavid** [comment]
@naima-hossain I have deleted this test case (SupportsCoauthPrereq) locally in code. Then, there is another invalid test case (deleted too).
But if you can have your solution on public IP (domain) the best solution is to upload file with .wopitest extension into your solution and open (wopi doscovery flow). There is UI with all the test cases functional.

**Comment by naima-hossain** [comment]
@EislerDavid thanks for replying. Can you please explain a bit on 

> "But if you can have your solution on public IP (domain) the best solution is to upload file with .wopitest extension into your solution and open (wopi doscovery flow). There is UI with all the test cases functional."
My wopi src is in a public url. When you are saying solution, do you mean the wopi source? Is there any document for the case that you are talking about?

**Comment by EislerDavid** [comment]
@naima-hossain Just create any file and change extension to .wopitest. Then open it in office online and you will see UI with all test cases.

**Comment by kolAflash** [comment]
> [@naima-hossain](https://github.com/naima-hossain) I have deleted this test case (SupportsCoauthPrereq) locally in code. Then, there is another invalid test case (deleted too). But if you can have your solution on public IP (domain) the best solution is to upload file with .wopitest extension into your solution and open (wopi doscovery flow). There is UI with all the test cases functional.

Same for me, running Debian-12 with [net8.0 installed as described here](https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian?tabs=dotnet8#debian-12).

`SupportsCoauthPrereq` and `SupportsChunkedFileTransferPrereq` don't seem to work.  
In `TestCases.xml` I deleted:  
```
<TestCase Name="SupportsCoauthPrereq" Category="WopiCoauth">
//...
</TestCase>

<TestCase Name="SupportsChunkedFileTransferPrereq" Category="WopiCoauth">
// ...
</TestCase>

// all lines being one of these:
<PrereqTest>SupportsCoauthPrereq</PrereqTest>
<PrereqTest>SupportsChunkedFileTransferPrereq</PrereqTest>
```

&nbsp;

Seems related:
- #117
