### ISSUE TITLE
System.OperationCanceledException: The operation was canceled.

### ISSUE THREAD

**Issue by cgruber0** [microsoft/wopi-validator-core#89]
Hi, 

when using the Docker version of this tool, I randomly get errors like this: 

`System.OperationCanceledException: The operation was canceled.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.Office.WopiValidator.Core.Requests.RequestBase.ExecuteRequest(RequestExecutionData executionData, String userAgent) in C:\code\wopi-validator-core\src\WopiValidator.Core\Requests\RequestBase.cs:line 96
   at Microsoft.Office.WopiValidator.Core.Requests.WopiRequest.Execute(String endpointAddress, String accessToken, Int64 accessTokenTtl, ITestCase testCase, Dictionary`2 savedState, IResourceManager resourceManager, String userAgent, RSACryptoServiceProvider proofKeyProviderNew, RSACryptoServiceProvider proofKeyProviderOld) in C:\code\wopi-validator-core\src\WopiValidator.Core\Requests\WopiRequest.cs:line 108
   at Microsoft.Office.WopiValidator.Core.TestCaseExecutor.ExecuteTestCase(ITestCase testCase) in C:\code\wopi-validator-core\src\WopiValidator.Core\TestCaseExecutor.cs:line 81
   at Microsoft.Office.WopiValidator.Core.TestCaseExecutor.Execute() in C:\code\wopi-validator-core\src\WopiValidator.Core\TestCaseExecutor.cs:line 57
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at Microsoft.Office.WopiValidator.Program.Execute(Options options) in C:\code\wopi-validator-core\src\WopiValidator\Program.cs:line 102
   at Microsoft.Office.WopiValidator.Program.Main(String[] args) in C:\code\wopi-validator-core\src\WopiValidator\Program.cs:line 44`

The exception occurs really randomly and not after a certain test. So it can be that there are 10 successfull tests and then suddenly, the error occurs.

Before the exception occurs, the program stands still for ~1 minute. My API endpoints are fully operational and available. 

OS: Ubuntu 18.04
Docker: 18.09.7

Any idea? Thanks!

**Comment by tylerbutler** [comment]
@enigma969 Thanks for the bug report! My hunch is that this is related in some way to Docker's network stack, but that's mostly a guess. I've not been able to reproduce it yet, but I haven't tried on Ubuntu.

**Comment by v-stefansi** [comment]
We are in the process of closing WOPI Validator GitHub.  If you still need help with this issue, please reach out to the CSPP partner Yammer channel or contact csppteam@microsoft.com.
